name: Podman CI Demo

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'Containerfile'
    pull_request:
        paths:
            - 'src/**'
            - 'Containerfile'
jobs:
    build:
        name: Build the Code
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repo
            - name: Checkout code
              uses: actions/checkout@v3
            
              # Step 2: Install Podman
            - name: Install Podman
              run: |
                sudo apt-get update
                sudo apt-get install -y podman
            
                # Step 3: Verify Podman installation
            - name: Check Podman Version
              run: podman --version
            
              # Step 4: Build the container
            - name: Build Container
              run: podman build -t podman-ci-demo .
            
              # Step 5: Test the executable inside the container
            - name: Run Executable
              run: podman run --name ci-container podman-ci-demo
            
              # Step 6: Extract the executable file as an artifact
            - name: Extract Artifacts
              if: success()
              run: podman cp ci-container:/app/hello ./hello

            # Step 7: Upload artifact to GitHub
            - name: Upload Artifact
              if: success()
              uses: actions/upload-artifact@v3
              with:
                name: hello-executable
                path: ./hello

            # Step 8: Remove Container in case it is running on a self-hosted runner
            - name: Remove Container
              if: always()
              # || true is to ensure it doesn't fail if there is no image
              run: podman rm ci-container || true