name: Podman CI Demo

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'Containerfile'
    pull_request:
        paths:
            - 'src/**'
            - 'Containerfile'
